package fr.byob.gae.server.rest.db.dao.impl;

import com.googlecode.objectify.Key;
import com.googlecode.objectify.Objectify;
import com.googlecode.objectify.ObjectifyService;

import fr.byob.gae.server.rest.db.bean.Car;
import fr.byob.gae.server.rest.db.dao.CarDAO;

public class CarDAOImpl implements CarDAO {

	public Car getCar(Long id) {
		Objectify ofy = ObjectifyService.begin();
		return ofy.get(new Key<Car>(Car.class, id));
	}

	public void addCar(Car car) {
		Objectify ofy = ObjectifyService.begin();
		ofy.put(car);
		assert car.getId() != null; // id was autogenerated
	}

	public void deleteCar(Car car) {
		Objectify ofy = ObjectifyService.begin();
		ofy.delete(car);
	}

	public void updateCar(Car car) {
		assert car.getId() == null; // car must bu already persisted
		Objectify ofy = ObjectifyService.begin();
		ofy.put(car);
	}
}
